### ISSUE TITLE
No way to fall back to queue's settings for visibilityTimeout and waitTimeSeconds

### ISSUE THREAD

**Issue by kvnflm** [zio/zio-sqs#253]
These two settings are also present on SQS queues themselves, and if a `ReceiveMessages` call doesn't include them, the queue's values will be used. Currently in zio-sqs, it seems like it's not possible to fall back to the queue's settings -- you can either provide explicit values, or if you don't provide anything, it will use default settings of 30 for `visibilityTimeout` and 20 for `waitTimeSeconds`.

Perhaps by making these settings `Option`s, a `None` value could mean that they won't be set on the `ReceiveMessageRequest`, and the queue's settings will be used?

For references, these are the only pages so far that I've been able to find in AWS docs that describes this behavior...
For visibilityTimeout: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html
For waitTimeSeconds: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html

**Comment by ghostdogpr** [comment]
I agree (not sure, and it's quite dirty but if you set those values to `null` it might work).

By any chance, would you like to become a contributor and implement this? 😄

**Comment by kvnflm** [comment]
Sure, I should have some time in the next few days to work on this.
