### ISSUE TITLE
Add 2.13 build/CI

### ISSUE THREAD

**Issue by ghostdogpr** [zio/zio-sqs#29]
ZIO now support Scala 2.13, so this library should too.

**Comment by pravin-raha** [comment]
We have to wait for elasticmq to support 2.13

**Comment by ghostdogpr** [comment]
@pravin-raha thanks!

**Comment by solicode** [comment]
Another option could be to run elasticmq/localstack SQS outside the Scala project itself through Docker and test against it that way.

**Comment by ghostdogpr** [comment]
Yeah it’s an option, just less straightforward than the current solution. Or we could just disable the tests for 2.13 but still publish the library, until the dependency is available.

**Comment by solicode** [comment]
Yeah, it does complicate the setup a bit (waiting for the service to come online and such before running the tests).

Publishing without the tests for 2.13 also works. I'm fine with it, but it's not my call. 😛

**Comment by solicode** [comment]
If you're okay with disabling the tests for 2.13, I don't mind doing the PR (haven't looked yet, but it might just be SBT changes assuming source doesn't break). I'm looking into integrating zio-sqs in one of my work projects.

**Comment by solicode** [comment]
Sorry for being impatient. I went ahead and created the PR.

**Comment by ghostdogpr** [comment]
@solicode no that’s good! I’m traveling now but I’ll check it as soon as I get back. I can also cut a release once it’s merged.
