### ISSUE TITLE
Make the SqsStream infinite

### ISSUE THREAD

**Issue by melgenek** [zio/zio-sqs#443]
The current signature of the `SqsStream.apply` is
```
  def apply(
    queueUrl: String,
    settings: SqsStreamSettings = SqsStreamSettings()
  ): ZStream[Sqs, Throwable, Message.ReadOnly]
```

The stream stops after the first exception that is received in the sqs call. The exceptions can be intermittent, for example,
```
software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.
....
```
The next call to sqs after such an exception would be successful.

In most situations (at least those that I've seen) the sqs is supposed to be consumed infinitely. The exceptions are logged and retried.

With the current `SqsStream.apply` there could be a couple of solutions to achieve the infinite stream:
1) restart the program when the stream fails
```
SqsStream(???, ???)
      .runDrain
      .exitCode
```
In environments like ElasticBeanstalk it's not ideal because the ec2 restart is quite slow.
2) consume a new same stream when the current stream fails
```
          def infiniteStream(): ZStream[Sqs, Nothing, Message] = {
            SqsStream(???, ???).catchAll(_ => infiniteStream)
          }
``` 

In both situations, some additional code is required to continue consuming the messages.

My proposal is to have an additional method in the zio-sqs SqsStream, so that the library provides a short solution for an infinite sqs stream.

Its signature would be 
```
object SqsStream {
...

  def infinite(
    queueUrl: String,
    settings: SqsStreamSettings = SqsStreamSettings()
  ): ZStream[Sqs, Nothing, Either[Throwable, Message.ReadOnly]] = ???
}

```

If this proposal sounds reasonable, I can provide a pr.

**Comment by ghostdogpr** [comment]
I think it makes sense to have this option in addition to the existing one. To be consistent with `Producer` I think it would be good to mimic `methods that do not fail the operation but return ErrorOrEvent[T] (defied as Either[ProducerError[T], ProducerEvent[T]])`, in particular `sendStreamE`.

**Comment by melgenek** [comment]
I implemented the proposal and it doesn't seem to be reasonable to me any more :slightly_smiling_face:.

Returning `Either[Throwable, Message.ReadOnly]` would mean that the next request to sqs follows the failed one without giving any time to the system to recover. So in my example, the dns issue can last some seconds or minutes and the stream would be flooded with Left values. This can cause performance issues, the monitoring and logging systems will be full of errors etc.

The better approach for my desire of having an infinite stream is retiring the failed stream exponentially. The code would look like 
```
SqsStream(???, ???)
      .runDrain
      .retry(Schedule.exponential(1.second) || Schedule.spaced(4.second) )
```
