### ISSUE TITLE
SqsProducer stops working after error from SQS

### ISSUE THREAD

**Issue by aquamatthias** [zio/zio-sqs#456]
Hey. We are using zio-sqs version 0.3.2 to receive and produce sqs messages. 
For the sending part we see a strange behaviour, in case SQS is not reachable or rejects a request:

The sending fails (which is correct) but the producer is not usable afterwards.
All messages that get produced afterwards are stuck forever (fiber does not return).

Since the code is not very complex I pasted it here.
Are we doing anything wrong, or what could cause this issue?

The producer that we use looks like this:

```scala
trait SqsProducer {
  def produce(message: ProducerEvent[String]): IO[Error, ProducerEvent[String]]
}
object SqsProducer {
  def createProducer(
      queueName: String,
      sqsConfig: SqsConfig,
      producerSettings: ProducerSettings
  ): ZManaged[Clock, Throwable, SqsProducer] = {
    def requestQueueUrl(sqs: SqsAsyncClient) =
      ZIO.fromCompletionStage(sqs.getQueueUrl(GetQueueUrlRequest.builder().queueName(queueName).build()))

    for {
      sqs      <- Sqs.fromConfig(sqsConfig)
      queueUrl <- ZManaged.fromEffect(requestQueueUrl(sqs))
      producer <- Producer.make(sqs, queueUrl.queueUrl(), Serializer.serializeString, producerSettings)
    } yield new SqsProducer {
      override def produce(message: ProducerEvent[String]): IO[Error, ProducerEvent[String]] =
        producer.produce(message).mapError(Error.SqsAccessError)
    }
  }
}

val producer: SqsProducer = ... 
producer.produce(event) 
// issue with SQS --> fails with SqsAccessError
producer.produce(anotherEvent)
// fiber never returns
```

**Comment by ghostdogpr** [comment]
@gchudnov any idea about that? I'm not that familiar with the producer code now...

**Comment by gchudnov** [comment]
checking..

**Comment by gchudnov** [comment]
reproduced the problem,
working on the fix.

**Comment by gchudnov** [comment]
@ghostdogpr 
made a PR, please review.

sorry for delay, the day was a bit messy =(

**Comment by ghostdogpr** [comment]
I released a new version with the fix.
