### ISSUE TITLE
Release for the latest ZConfig

### ISSUE THREAD

**Issue by gipeshka** [zio/zio-sqs#514]
Hello.

I see there have been no releases since last year. The other ZIO libs have quite advanced, because of that it's difficult to use latest release of zio-sqs together with latest ZConfig eg. Is there a plan to release zio-sqs with the most recent updates? Everything seems to be up to date in master thanks to Steward.

Thanks!

**Comment by ghostdogpr** [comment]
That's because ZIO is binary compatible since version 1.0, so you can use the latest ZIO with the version of zio-sqs published last year. Let me know if you meet any issue.

**Comment by gipeshka** [comment]
hm, I see the following error when updating `zio-config-magnolia` and `zio-config-typesafe` from 1.0.0-RC30-1 to 1.0.0:
```
[error] Symbol 'type zio.config.ConfigModule.ZConfig' is missing from the classpath.
[error] This symbol is required by 'method io.github.vigoo.zioaws.core.config.configured'.
[error] Make sure that type ZConfig is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of zio.config.ConfigModule.
[error]         zioaws.core.config.configured() >>
```

**Comment by ghostdogpr** [comment]
Ah, maybe because of the version of zio-config used transitively by zio-aws, and this one is not binary compatible. I'll release then!

**Comment by ghostdogpr** [comment]
Release: https://github.com/zio/zio-sqs/releases/tag/v0.4.2

CI is in progress!

**Comment by ghostdogpr** [comment]
Done! Closing this issue 😄
