### ISSUE TITLE
Update/cross-compile for scala 3

### ISSUE THREAD

**Issue by Esardes** [zio/zio-sqs#632]

**Comment by kirillsalykin** [comment]
Any updates on this?

**Comment by kirillsalykin** [comment]
Please check if https://github.com/zio/zio-sqs/pull/659 enough to resolve this

**Comment by kirillsalykin** [comment]
seems it is more complicated, `zio-sqs` depends on `elasticmq` which depends on `akka-http`. https://github.com/softwaremill/elasticmq/issues/637
As an alternative - testcontainers + localstack  can be used.

**Comment by ghostdogpr** [comment]
> seems it is more complicated, `zio-sqs` depends on `elasticmq` which depends on `akka-http`. [softwaremill/elasticmq#637](https://github.com/softwaremill/elasticmq/issues/637) As an alternative - testcontainers + localstack can be used.

Yeah, sounds like the right alternative. Better not to depend on akka anymore and I don't think elasticmq is going to be migrated overnight.

**Comment by rstradling** [comment]
See #676 for an approach for the short-term.
