### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by inbrain** [zio/zio-sqs#739]
Please make a release that will include recently updated `zio-aws  7.28.26.1` (Steward did its job already integrating it). Current version causes runtime crashes if brought together with updated `zio-aws`

**Comment by mijicd** [comment]
I've triggered the 0.6.2 release, and I'll close the issue once it succeeds. cc @ghostdogpr

**Comment by mijicd** [comment]
Released https://github.com/zio/zio-sqs/releases/tag/v0.6.2

**Comment by calvinlfer** [comment]
Thanks @mijicd
